namespace ProjectController.TVControls;

public enum IRCommands
{ 
    BTN_DPAD_UP              ,
    BTN_DPAD_DOWN            ,
    KEY_OK                   ,
    BTN_DPAD_RIGHT           ,
    BTN_DPAD_LEFT            ,
    KEY_NUMERIC_0            ,
    KEY_NUMERIC_1            ,
    KEY_NUMERIC_2            ,
    KEY_NUMERIC_3            ,
    KEY_NUMERIC_4            ,
    KEY_NUMERIC_5            ,
    KEY_NUMERIC_6            ,
    KEY_NUMERIC_7            ,
    KEY_NUMERIC_8            ,
    KEY_NUMERIC_9            ,
    KEY_PAGEUP               ,
    KEY_PAGEDOWN             ,
    KEY_MUTE                 ,
    KEY_SUBTITLE             ,
    KEY_POWER                ,
    KEY_AUDIO                ,
    KEY_EPG                  ,
    KEY_FILE                 ,
    KEY_MENU                 ,
    KEY_EXIT                 ,
    KEY_FAVORITES            ,
    KEY_TV                   ,
    KEY_BACK                 ,
    KEY_INFO                 ,
    KEY_FORWARD              ,
    KEY_REWIND               ,
    KEY_PREVIOUS             ,
    KEY_NEXT                 ,
    KEY_PLAY                 ,
    KEY_PAUSE                ,
    KEY_STOP                 ,
    KEY_RECORD               ,
    KEY_RED                  ,
    KEY_GREEN                ,
    KEY_YELLOW               ,
    KEY_BLUE                 ,
}