version: '3.8'
services:
  projectorcontroller:
    image: projectorcontroller
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/arm64
        - VUE_APP_API_URL=192.168.0.174
        - VUE_APP_PORT=8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:80"
      - "19521:19521"
      - "5037:5037"
      - "5555:5555"
    volumes:
      - /home/logs:/app/logs # Maps the log directory
      - /var/run/lirc:/var/run/lirc # Maps the LIRC socket directory
    devices:
      - /dev/lirc0:/dev/lirc0 # Maps the LIRC device
    privileged: true # Grants elevated privileges to access host hardware
    restart: always