version: '3.8'
services:
  projectorcontroller:
    image: projectorcontroller
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_PORT=8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CustomConfig__IPAddress=localhost
      - CustomConfig__DebugVersion=false
    ports:
      - "8081:80"
      - "19521:19521"