version: '3.8'
services:
  projectorcontroller:
    image: projectorcontroller
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/arm64
        - VUE_APP_API_URL=192.168.0.174
        - VUE_APP_PORT=8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:80"
      - "19521:19521"
    volumes:
      - /home/logs:/app/logs