version: '3.8'
services:
  backend:
    image: projectcontroller
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        - VUE_APP_API_URL=backend
#        - VUE_APP_PORT=8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CustomConfig__IPAddress=localhost
      - CustomConfig__DebugVersion=false
    ports:
      - "8081:80"
      - "19521:19521"
