export enum ProjectorCommands
{
    SystemControlStartCommunication,
    SystemControlPowerQuery,
    SystemControlPowerOff,
    SystemControlPowerOn,
    SystemControlVolumeMuteOn,
    SystemControlVolumeMuteOff,
    SystemControlVolumeMuteQuery,
    SystemControlVolumeUp,
    SystemControlVolumeDown,
    SystemControlVolumeQuery,
    SystemControlSourceHDMI1,
    SystemControlSourceHDMI2,
    SystemControlSourceHDMI3,
    SystemControlSourceHDMILAN,
    SystemControlSourceQuery,
    SystemControlSourceListQuery,
    SystemInformationProjectorNameQuery,
    SystemInformationSerialNumberQuery,
    SystemInformationErrorQuery,
    SystemInformationLampHoursQuery,
    SystemInformationOperationalTimeQuery,
    SystemInformationSignalStatusQuery,
    ImageControlNaturalColorMode,
    ImageControlImageReverseHorizontalOn,
    ImageControlImageReverseHorizontalOff,
    ImageControlImageReverseHorizontalQuery,
    ImageControlImageReverseVerticalOn,
    ImageControlImageReverseVerticalOff,
    ImageControlImageReverseVerticalQuery,
    ImageControlBrightnessUp,
    ImageControlBrightnessDown,
    ImageControlBrightnessQuery,
    ImageControlStatusLEDIlluminationOn,
    ImageControlStatusLEDIlluminationOff,
    ImageControlStatusLEDIlluminationQuery,
    KeyControlPower,
    KeyControlMenu,
    KeyControlUp,
    KeyControlDown,
    KeyControlLeft,
    KeyControlRight,
    KeyControlEnter,
    KeyControlHome,
    KeyControlVolumeUp,
    KeyControlVolumeDown,
    KeyControlAVMuteBlank,
    KeyControlKeysTone,
    KeyControlHDMILink,
    KeyControlPlay,
    KeyControlStop,
    KeyControlPause,
    KeyControlRewind,
    KeyControlFastForward,
    KeyControlBackward,
    KeyControlForward,
    KeyControlMute,
    KeyControlLinkMenu,
    IRHome,
    IRESC,
    IREnter,
    IRPointerUp,
    IRPointerDown,
    IRPointerLeft,
    IRPointerRight,
}

export enum PowerStatusProjector
{
    StandbyNetworkOff = 0,
    LampOn = 1,
    Warmup = 2,
    CoolDown = 3,
    StandbyNetworkOn = 4,
    AbnormalityStandby = 5,
    Unknown = 6
}

export enum ToggleStatusGui
{
    Off = 0,
    On = 1,
    Pending = 2,
}